These are using the same data like what we have been using before. 

https://www.kdnuggets.com/2017/04/simple-understand-gradient-descent-algorithm.html

https://machinelearningmastery.com/gradient-descent-for-machine-learning/

In [4]:
import numpy as np

In [5]:
filehandle = 'C:\\Ellen\\Udacity\\Computer_Vision\\data\\DL_Data\\data.csv'

In [6]:
data=np.loadtxt(filehandle,skiprows=0,delimiter=",")
#print(data)
print(data.shape) # 100, 3

(100, 3)


In [23]:
X = data[:,0:2]
#X
print(X.shape)
y = data[:,2:4]
#Y

(100, 2)


In [33]:
import numpy as np
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

def sigmoid(x): # Sigmoid function
    return 1/(1+np.exp(-x))
def sigmoid_prime(x): # Derivative of the sigmoid function - see Udacity notes
    return sigmoid(x)*(1-sigmoid(x))
def prediction(X, W, b):
    return sigmoid(np.matmul(X,W)+b)
def error_vector(y, y_hat): 
    return [-y[i]*np.log(y_hat[i]) - (1-y[i])*np.log(1-y_hat[i]) for i in range(len(y))]
def error(y, y_hat):
    ev = error_vector(y, y_hat)
    return sum(ev)/len(ev)

This function should receive X and y, and return a list of errors given by the formula for the gradient:
$$ −(y− \hat{y})(x_{1}, ...x_{n})$$

In [36]:
# TODO: Fill in the code below to calculate the gradient of the error function.
# The result should be a list of three lists:
# The first list should contain the gradient (partial derivatives) with respect to w1
# The second list should contain the gradient (partial derivatives) with respect to w2
# The third list should contain the gradient (partial derivatives) with respect to b 
    
def dErrors(X, y, y_hat):
    #DerrorsDx1 = -(y-y_hat)*Xi
    DErrorsDx1 = [-X[i][0]*(y[i]-y_hat[i]) for i in range(len(y))] # This computes the error function for each line
    DErrorsDx2 = [-X[i][1]*(y[i]-y_hat[i]) for i in range(len(y))] 
    DErrorsDb = [-(y[i]-y_hat[i]) for i in range(len(y))]
    return DErrorsDx1, DErrorsDx2, DErrorsDb

In [37]:
# TODO: Fill in the code below to implement the gradient descent step.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b.
# It should calculate the prediction, the gradients, and use them to
# update the weights and bias W, b. Then return W and b.
# The error e will be calculated and returned for you, for plotting purposes.
def gradientDescentStep(X, y, W, b, learn_rate = 0.01):
    y_hat = prediction(X,W,b)
    errors = error_vector(y, y_hat)
    derivErrors = dErrors(X, y, y_hat)
    W[0] -= sum(derivErrors[0])*learn_rate # See formula Lazy programmer
    W[1] -= sum(derivErrors[1])*learn_rate # Same
    b -= sum(derivErrors[2])*learn_rate
    return W, b, sum(errors)

In [38]:
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainLR(X, y, learn_rate = 0.01, num_epochs = 100):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    # Initialize the weights randomly
    W = np.array(np.random.rand(2,1))*2 -1
    b = np.random.rand(1)[0]*2 - 1
    # These are the solution lines that get plotted below.
    boundary_lines = []
    errors = []
    for i in range(num_epochs):
        # In each epoch, we apply the gradient descent step.
        W, b, error = gradientDescentStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
        errors.append(error)
    return boundary_lines, errors

In [39]:
trainLR(X, y, learn_rate = 0.01, num_epochs = 100)

([(array([ 0.61819151]), array([-0.39014295])),
  (array([ 1.02795525]), array([-0.31133603])),
  (array([ 1.52309412]), array([-0.29899588])),
  (array([ 2.15036792]), array([-0.36924468])),
  (array([ 3.01018138]), array([-0.54887429])),
  (array([ 4.32500124]), array([-0.9027684])),
  (array([ 6.69017386]), array([-1.61750284])),
  (array([ 12.42942205]), array([-3.4419656])),
  (array([ 48.80781988]), array([-15.22202259])),
  (array([-30.64172862]), array([ 10.58683365])),
  (array([-12.44748108]), array([ 4.69627049])),
  (array([-8.09145274]), array([ 3.29358548])),
  (array([-6.13189927]), array([ 2.66599553])),
  (array([-5.01638375]), array([ 2.31035844])),
  (array([-4.29562258]), array([ 2.08138171])),
  (array([-3.79132609]), array([ 1.92157928])),
  (array([-3.41860272]), array([ 1.80367222])),
  (array([-3.13185796]), array([ 1.7130604])),
  (array([-2.90440207]), array([ 1.64122591])),
  (array([-2.7195661]), array([ 1.582865])),
  (array([-2.5663993]), array([ 1.534502

## Understanding the code below

In [9]:
x_min, x_max = min(X.T[0]), max(X.T[0])
y_min, y_max = min(X.T[1]), max(X.T[1])
print(x_min, x_max, y_min, y_max)

0.0084492 1.0 -0.063669 1.0


In [13]:
# Initialize the weights randomly
W = np.array(np.random.rand(2,1))*2 -1
b = np.random.rand(1)[0]*2 - 1
print(W)
print()
print(b)

[[ 0.55758717]
 [-0.92963451]]

-0.690156209521


In [14]:
boundary_lines = []
errors = []

In [17]:
#for i in range(100):
    #print(i)
epochs = 0    

In [24]:
def dErrors(X):
    DErrorsDx1 = [-X[i] for i in range(len(y))]
    return DErrorsDx1

In [41]:
y_hat = prediction(X,W,b)
y_hat

array([[ 0.45121447],
       [ 0.3098967 ],
       [ 0.34766015],
       [ 0.28512086],
       [ 0.32432335],
       [ 0.34623058],
       [ 0.30037313],
       [ 0.32403545],
       [ 0.28850812],
       [ 0.31180556],
       [ 0.30737621],
       [ 0.28227187],
       [ 0.28021085],
       [ 0.30789433],
       [ 0.29709056],
       [ 0.34484475],
       [ 0.35133883],
       [ 0.32210634],
       [ 0.29279124],
       [ 0.29503922],
       [ 0.30208816],
       [ 0.27124544],
       [ 0.30252845],
       [ 0.28252598],
       [ 0.34362474],
       [ 0.23655667],
       [ 0.24249889],
       [ 0.2980463 ],
       [ 0.3643034 ],
       [ 0.34147619],
       [ 0.28409274],
       [ 0.37795294],
       [ 0.25269645],
       [ 0.27891902],
       [ 0.29531222],
       [ 0.30253161],
       [ 0.32108911],
       [ 0.28759081],
       [ 0.33300149],
       [ 0.34025744],
       [ 0.30067175],
       [ 0.27284032],
       [ 0.34920882],
       [ 0.2634655 ],
       [ 0.33415029],
       [ 0

In [42]:
errors = error_vector(y, y_hat)
errors

[array([ 0.79581251]),
 array([ 1.17151626]),
 array([ 1.05652984]),
 array([ 1.25484213]),
 array([ 1.12601426]),
 array([ 1.0606503]),
 array([ 1.2027298]),
 array([ 1.12690237]),
 array([ 1.24303205]),
 array([ 1.16537551]),
 array([ 1.17968283]),
 array([ 1.2648846]),
 array([ 1.27221293]),
 array([ 1.17799863]),
 array([ 1.21371827]),
 array([ 1.06466097]),
 array([ 1.04600418]),
 array([ 1.13287353]),
 array([ 1.22829543]),
 array([ 1.22064699]),
 array([ 1.19703638]),
 array([ 1.3047312]),
 array([ 1.19557997]),
 array([ 1.26398475]),
 array([ 1.0682051]),
 array([ 1.44156747]),
 array([ 1.41675813]),
 array([ 1.21050644]),
 array([ 1.00976824]),
 array([ 1.07447732]),
 array([ 1.25845454]),
 array([ 0.97298558]),
 array([ 1.37556632]),
 array([ 1.27683379]),
 array([ 1.2197221]),
 array([ 1.19556952]),
 array([ 1.13603659]),
 array([ 1.2462166]),
 array([ 1.09960831]),
 array([ 1.07805278]),
 array([ 1.20173615]),
 array([ 1.29886855]),
 array([ 1.05208519]),
 array([ 1.3338328